#pragma once

#include "tools/FunctionTool.hpp"

namespace ORION
{
    /// @brief  A tool that can remember knowledge
    class RememberKnowledgeFunctionTool final : public FunctionTool
    {
    public:
        struct Statics
        {
            /// @brief A function that remembers knowledge
            constexpr static auto REMEMBER_KNOWLEDGE = R"(
            {
                "description" : "Stores knowledge in the assistant's memory. Confirm with user exact information being stored. Examine function return to see if you need to run update_knowledge instead.",
                "name" : "remember_knowledge",
                "parameters" : {
                    "type" : "object",
                    "properties" : {
                        "knowledge_type" : {
                            "type" : "string",
                            "enum" : [ "user_personal_info", "user_interests", "family_personal_info", "family_interests", "user_preferences", "unknown" ],
                            "description" : "The type of knowledge to store, select unknown if doesn't fit any of the other types."
                        },
                        "knowledge" : {
                            "type" : "string",
                            "description" : "The knowledge to store. A summary generated by examining the current conversation and intelligently determining the knowledge."
                        },
                        "knowledge_subject_and_tags" : {
                            "type" : "array",
                            "items" : {
                                "type" : "string"
                            },
                            "description" : "MUST contain a list of at LEAST 10 generated TAGS that describes the content. For example, if the knowledge is about a person in a red shirt and black pants walking down the road, the tags could be 'person', 'red shirt', 'black pants', 'walking', 'road', 'outside', 'person walking', 'clothing', 'color', 'activity'."
                        }
                    },
                    "required" : [ "knowledge_type", "knowledge", "knowledge_subject_and_tags"]
                }
            })";
        };

        inline RememberKnowledgeFunctionTool()
            : FunctionTool(Statics::REMEMBER_KNOWLEDGE)
        {
        }

        virtual std::string Execute(class Orion& Orion, const web::json::value& Parameters) override;
    };
} // namespace ORION
